SELECT
LPA.IDPROC,
LPA.CODPRODPA,
PRC.CODPRC,
PRC.DESCRABREV,
PRC.VERSAO VERSAO_PROCESSO,
ATV.IDPROC ID_PROCESSO,
ATV.IDEFX ID_ATIVIDADE,
EFX.DESCRICAO ATIVIDADE,
CTA.CODPRODTAR,
PRO.DESCRPROD,
CTA.QTD,
CTA.CODVOL,
nvl((SELECT MAX(SEQ) FROM AD_ZBVCIP WHERE NUNICO = :P_NUNICO),0)+ROWNUM AS SEQMP,
NVL(CUS.CUSMEDICM,0) CUSMEDICM,
NVL(CUS.CUSSEMICM,0) CUSSEMICM

FROM AD_ZBVCAB CAB
INNER JOIN TPRPRC PRC ON PRC.IDPROC = CAB.IDPROC
INNER JOIN TPRLPA LPA ON LPA.IDPROC = PRC.IDPROC
                      AND LPA.CODPRODPA = CAB.CODPROD

INNER JOIN TPRATV ATV ON ATV.IDPROC = CAB.IDPROC
INNER JOIN TPREFX EFX ON ATV.IDEFX = EFX.IDEFX
INNER JOIN TPRTCA CTA ON CTA.IDPROC = CAB.IDPROC
                      AND CTA.IDEFX = ATV.IDEFX
                      AND CTA.CODPRODPA = CAB.CODPROD
INNER JOIN TGFPRO PRO ON PRO.CODPROD = CTA.CODPRODTAR
LEFT JOIN (SELECT CUS.CODPROD, CUS.DTATUAL, CUS.CUSMEDICM, CUS.CUSSEMICM FROM TGFCUS CUS
INNER JOIN (SELECT MAX(DTATUAL)DTATUAL, CODPROD FROM TGFCUS GROUP BY CODPROD ) MAX_CUS ON MAX_CUS.CODPROD = CUS.CODPROD
                                                                      AND MAX_CUS.DTATUAL = CUS.DTATUAL
) CUS ON CUS.CODPROD = CTA.CODPRODTAR
WHERE CAB.NUNICO = :P_NUNICO