SELECT
LPA.IDPROC,
LPA.CODPRODPA,
PRC.CODPRC,
PRC.DESCRABREV,
PRC.VERSAO VERSAO_PROCESSO,
'N/A Por processo.' ATIVIDADE,
TPP.CODPRODTAR,
PRO.DESCRPROD,
TPP.QTD,
TPP.CODVOL,
nvl((SELECT MAX(SEQ) FROM AD_ZBVCIP WHERE NUNICO = :P_NUNICO),0)+ROWNUM AS SEQMP,
NVL(CUS.CUSMEDICM,0) CUSMEDICM,
NVL(CUS.CUSSEMICM,0) CUSSEMICM

FROM AD_ZBVCAB CAB
INNER JOIN TPRPRC PRC ON PRC.IDPROC = CAB.IDPROC
INNER JOIN TPRLPA LPA ON LPA.IDPROC = PRC.IDPROC
                      AND LPA.CODPRODPA = CAB.CODPROD
INNER JOIN TPRTPP TPP ON TPP.IDPROC = CAB.IDPROC
                      AND TPP.CODPRODPA = LPA.CODPRODPA

INNER JOIN TGFPRO PRO ON PRO.CODPROD = TPP.CODPRODTAR
LEFT JOIN (SELECT CUS.CODPROD, CUS.DTATUAL, CUS.CUSMEDICM, CUS.CUSSEMICM FROM TGFCUS CUS
INNER JOIN (SELECT MAX(DTATUAL)DTATUAL, CODPROD FROM TGFCUS GROUP BY CODPROD ) MAX_CUS ON MAX_CUS.CODPROD = CUS.CODPROD
                                                                      AND MAX_CUS.DTATUAL = CUS.DTATUAL
) CUS ON CUS.CODPROD = TPP.CODPRODTAR
WHERE CAB.NUNICO = :P_NUNICO