SELECT
LPA.IDPROC,
LPA.CODPRODPA,
PRO.DESCRPROD,
PRC.CODPRC,
PRC.DESCRABREV,
PRC.VERSAO VERSAO_PROCESSO,
ATV.IDPROC ID_PROCESSO,
ATV.IDEFX ID_ATIVIDADE,
EFX.DESCRICAO ATIVIDADE,
LMP.CODPRODMP,
PMP.DESCRPROD DESCRPRODMP,
LMP.QTDMISTURA,
LMP.CODVOL,
ROWNUM AS SEQMP,
NVL(CUS.CUSMEDICM,0) CUSMEDICM,
NVL(CUS.CUSSEMICM,0) CUSSEMICM



FROM AD_ZBVCAB CAB
INNER JOIN TPRPRC PRC ON PRC.IDPROC = CAB.IDPROC
INNER JOIN TPRLPA LPA ON LPA.IDPROC = PRC.IDPROC
                      AND LPA.CODPRODPA = CAB.CODPROD
INNER JOIN TGFPRO PRO ON PRO.CODPROD = LPA.CODPRODPA
INNER JOIN TPRATV ATV ON ATV.IDPROC = CAB.IDPROC
INNER JOIN TPRLMP LMP ON LMP.IDEFX = ATV.IDEFX
                      AND LMP.CODPRODPA = LPA.CODPRODPA
INNER JOIN TPREFX EFX ON ATV.IDEFX = EFX.IDEFX
INNER JOIN TGFPRO PMP ON PMP.CODPROD = LMP.CODPRODMP
LEFT JOIN (SELECT CUS.CODPROD, CUS.DTATUAL, CUS.CUSMEDICM, CUS.CUSSEMICM FROM TGFCUS CUS
INNER JOIN (SELECT MAX(DTATUAL)DTATUAL, CODPROD FROM TGFCUS GROUP BY CODPROD ) MAX_CUS ON MAX_CUS.CODPROD = CUS.CODPROD
                                                                      AND MAX_CUS.DTATUAL = CUS.DTATUAL
) CUS ON CUS.CODPROD = LMP.CODPRODMP

WHERE CAB.NUNICO = :P_NUNICO
ORDER BY LMP.CODPRODMP ASC