WITH MKP AS (
    SELECT *
    FROM (
        SELECT M.*,
               ROW_NUMBER() OVER (PARTITION BY NUNICO ORDER BY SEQ DESC) RN
        FROM AD_ZBVMKP M
    )
    WHERE RN = 1
),

MP AS (
    SELECT
        NUNICO,
        SUM(
            NVL((QTDBRUTO*VLRUNITSEMICMS),0) - (NVL(QTDBRUTO-QTDLIQUIDO,0)*NVL(VLRSUCATA,0)) + NVL(VLRFRETE,0)
        ) AS TOTAL_MP
    FROM AD_ZBVITE
    GROUP BY NUNICO
),

CIP AS (
    SELECT
        NUNICO,
        SUM(NVL(VLRCUSTOPROCESSO,0)*NVL(QTD,0)) AS TOTAL_CIP
    FROM AD_ZBVCIP
    GROUP BY NUNICO
),

OUTR AS (
    SELECT
        NUNICO,
        SUM(NVL((QUANTIDADE * VLRUNIT) + VLRFRETE, 0)) AS TOTAL_OUTROS
    FROM AD_ZBVOUT
    GROUP BY NUNICO
),

FRE AS (
    SELECT
        NUNICO,
        SUM(NVL((DISTANCIA * CUSTOKM) / NULLIF(QTDPECAS, 0), 0)) AS VLRFRETE
    FROM AD_ZBVFRE
    GROUP BY NUNICO
),

AMO AS (
    SELECT
        INV.NUNICO,
        NVL(SUM(INV.QUANTIDADE * INV.CUSTO), 0) / NULLIF(CAB.VOLUME, 0) AS VLRUNITAMOR
    FROM AD_ZBVINV INV
    JOIN AD_ZBVCAB CAB
        ON CAB.NUNICO = INV.NUNICO
    GROUP BY INV.NUNICO, CAB.VOLUME
),

CALCULOS_BASE AS (

    SELECT
        CAB.NUNICO,

        NVL(MKP.ICMS,0)      AS ICMS,
        NVL(MKP.SGA,0)       AS SGA,
        NVL(MKP.LUCRO,0)     AS LUCRO,
        NVL(MKP.PISCOFINS,0) AS PISCOFINS,
        NVL(MKP.IRPJCSLL,0)  AS IRPJCSLL,
        NVL(MKP.OUTROS,0)    AS OUTROS,

        (
            (
                NVL(MP.TOTAL_MP,0)
                + NVL(CIP.TOTAL_CIP,0)
                + NVL(OUTR.TOTAL_OUTROS,0)
            )
            * (1 + NVL(CAB.SCRAP,0)/100)
            + NVL(FRE.VLRFRETE,0)
            + NVL(AMO.VLRUNITAMOR,0)
        ) AS CUSTO_TOTAL_COM_IMPACTOS

    FROM AD_ZBVCAB CAB
         LEFT JOIN MKP  ON MKP.NUNICO = CAB.NUNICO
         LEFT JOIN MP   ON MP.NUNICO = CAB.NUNICO
         LEFT JOIN CIP  ON CIP.NUNICO = CAB.NUNICO
         LEFT JOIN OUTR ON OUTR.NUNICO = CAB.NUNICO
         LEFT JOIN FRE  ON FRE.NUNICO = CAB.NUNICO
         LEFT JOIN AMO  ON AMO.NUNICO = CAB.NUNICO

    WHERE CAB.NUNICO = :P_NUNICO
),

RESULTADOS AS (

    SELECT
        B.*,
        ROUND(B.CUSTO_TOTAL_COM_IMPACTOS * (B.SGA/100), 4)          AS VLR_SGA_CALC,
        ROUND(B.CUSTO_TOTAL_COM_IMPACTOS * (NVL(B.LUCRO,0)/100), 4) AS VLR_LUCRO_CALC
    FROM CALCULOS_BASE B
)

SELECT
    R.NUNICO,

    ROUND(R.CUSTO_TOTAL_COM_IMPACTOS, 4) + R.VLR_SGA_CALC + R.VLR_LUCRO_CALC AS PRECOSEMIMPOSTO,

    (
        (ROUND(R.CUSTO_TOTAL_COM_IMPACTOS, 4) + R.VLR_SGA_CALC + R.VLR_LUCRO_CALC)
        / NULLIF(1 - (NVL(R.ICMS,0)/100), 0)
    ) / NULLIF(1 - (NVL(R.PISCOFINS+R.IRPJCSLL+R.OUTROS,0)/100), 0) AS PRECOCOMIMPOSTO

FROM RESULTADOS R