SELECT CASE
           WHEN EXISTS
                  (SELECT 1
                   FROM TPRLPA LPA
                   WHERE LPA.IDPROC = CAB.IDPROC
                     AND LPA.CODPRODPA = CAB.CODPROD) THEN 1
           ELSE 0
       END AS VALIDA,
       CAB.CODPROD,
       PRO.DESCRPROD,
       PRC.IDPROC,
       PRC.DESCRABREV,
       PRC.VERSAO
FROM AD_ZBVCAB CAB
INNER JOIN TGFPRO PRO ON PRO.CODPROD = CAB.CODPROD
INNER JOIN TPRPRC PRC ON PRC.IDPROC = CAB.IDPROC
WHERE CAB.NUNICO = :P_NUNICO